window.recipeCatalog = [
  {
    id: 67,
    name: 'Шакшука с беконом',
    url: 'https://food.ru/recipes/272671-shakshuka-s-bekonom',
    cuisine: 'Азиатская',
    meal_type: 'breakfast',
    cooking_time_min: 25,
    calories: 136,
    protein: 5.5,
    fat: 10.77,
    carbs: 3.34,
    price_per_serving: 140,
    servings: 3,
    ingredients: ['Куриное яйцо — 3 шт.', 'Сырокопченый бекон — 150 г', 'Помидор — 4 шт.', 'Красный болгарский перец — 0.5 шт.', 'Репчатый лук — 0.5 шт.', 'Чеснок — 2 зубчика', 'Копченая паприка — 1 ч.л.', 'Зира — 0.5 ч.л.', 'Черный молотый перец — по вкусу', 'Соль — по вкусу']
  },
  {
    id: 97,
    name: 'Шоколадное суфле',
    url: 'https://food.ru/recipes/55198-vkusnoe-shokoladnoe-sufle',
    cuisine: 'Французская',
    meal_type: 'dessert',
    cooking_time_min: 40,
    calories: 130.44,
    protein: 6.07,
    fat: 9.62,
    carbs: 4.8,
    price_per_serving: 85,
    servings: 4,
    ingredients: ['Шоколадно-ореховая паста — 180 г', 'Яйца — 2 шт.', 'Сахар — 8 г', 'Сливочное масло — 20 г', 'Какао-порошок — 25 г', 'Сахарная пудра — по вкусу']
  },
  {
    id: 98,
    name: 'Сэндвичи со свеклой, рикоттой и зеленью',
    url: 'https://food.ru/recipes/178754-sendvich-domashnii',
    cuisine: 'Европейская',
    meal_type: 'snack',
    cooking_time_min: 10,
    calories: 181.2,
    protein: 7.74,
    fat: 9.24,
    carbs: 16.4,
    price_per_serving: 110,
    servings: 2,
    ingredients: ['Ржаной тостовый хлеб — 160 г', 'Рукола — 20 г', 'Рикотта — 300 г', 'Свекла — 65 г', 'Чеснок — 5 г', 'Оливковое масло — 34 мл', 'Вода — 63 мл', 'Соль — 1 г']
  },
  {
    id: 99,
    name: 'Сэндвичи с тунцом и чесночным соусом',
    url: 'https://food.ru/recipes/109367-bystrye-sendvichi',
    cuisine: 'Американская',
    meal_type: 'snack',
    cooking_time_min: 20,
    calories: 275.2,
    protein: 4.26,
    fat: 17.77,
    carbs: 22.53,
    price_per_serving: 175,
    servings: 2,
    ingredients: ['Чиабатта — 350 г', 'Стебель сельдерея — 45 г', 'Помидор — 90 г', 'Лук-шалот — 30 г', 'Кинза — 12 г', 'Тунец в собственном соку — 100 г', 'Майонез — 125 г', 'Соус чили — 5 г', 'Вустерширский соус — 2.5 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу', 'Сливочное масло — 60 г', 'Чеснок — 10 г']
  },
  {
    id: 100,
    name: 'Тост с авокадо и крабовыми палочками',
    url: 'https://food.ru/recipes/271704-tost-s-avokado-i-krabovymi-palochkami',
    cuisine: 'Американская',
    meal_type: 'breakfast',
    cooking_time_min: 15,
    calories: 150.98,
    protein: 5.16,
    fat: 8.59,
    carbs: 13.11,
    price_per_serving: 135,
    servings: 2,
    ingredients: ['Тостовый хлеб — 80 г', 'Авокадо — 110 г', 'Куриное яйцо — 1 шт.', 'Крабовые палочки — 125 г', 'Помидоры черри — 100 г', 'Творожный сыр — 30 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 101,
    name: 'Клубничный овсяноблин с бананом',
    url: 'https://food.ru/recipes/271703-klubnichnyi-ovsjanoblin-s-bananom',
    cuisine: 'Русская',
    meal_type: 'breakfast',
    cooking_time_min: 25,
    calories: 196.05,
    protein: 6.72,
    fat: 8.46,
    carbs: 23.17,
    price_per_serving: 55,
    servings: 1,
    ingredients: ['Овсяные хлопья — 70 г', 'Банан — 75 г', 'Белок куриного яйца — 66 г', 'Молоко — 40 мл', 'Молотая корица — 1.5 г', 'Ванилин — 1 г', 'Растительное масло — 17 мл']
  },
  {
    id: 102,
    name: 'Запеченный омлет с треской',
    url: 'https://food.ru/recipes/271053-zapechennaja-s-omletom-treska',
    cuisine: 'Русская',
    meal_type: 'dinner',
    cooking_time_min: 35,
    calories: 139.08,
    protein: 13.17,
    fat: 8.08,
    carbs: 3.46,
    price_per_serving: 210,
    servings: 4,
    ingredients: ['Филе трески — 800 г', 'Полутвердый сыр — 200 г', 'Куриное яйцо — 6 шт.', 'Молоко 2.5% — 200 мл', 'Репчатый лук — 80 г', 'Морковь — 100 г', 'Соль — 7 г', 'Растительное масло — 51 мл']
  },
  {
    id: 103,
    name: 'Зеленый омлет в духовке',
    url: 'https://food.ru/recipes/271785-zelenyi-omlet-v-duhovke',
    cuisine: 'Европейская',
    meal_type: 'breakfast',
    cooking_time_min: 35,
    calories: 161.65,
    protein: 8.66,
    fat: 10.37,
    carbs: 7.34,
    price_per_serving: 95,
    servings: 4,
    ingredients: ['Яйца — 8 шт.', 'Шпинат — 300 г', 'Сливки 20% — 150 мл', 'Белый хлеб — 150 г', 'Твердый сыр — 50 г', 'Сливочное масло — 20 г', 'Чеснок — 5 г', 'Сладкая паприка — по вкусу', 'Соль — по вкусу', 'Черный перец молотый — по вкусу', 'Кинза — по вкусу']
  },
  {
    id: 68,
    name: 'Сэндвичи с горбушей и яйцом',
    url: 'https://food.ru/recipes/ingredienty/recepty-s-jaicom-i-rybnymi-konservami',
    cuisine: 'Русская',
    meal_type: 'snack',
    cooking_time_min: 10,
    calories: 171,
    protein: 10.98,
    fat: 6.9,
    carbs: 15.74,
    price_per_serving: 110,
    servings: 4,
    ingredients: ['Тостовый хлеб — 4 ломтика', 'Консервированная горбуша — 160 г', 'Куриное яйцо — 2 шт.', 'Сметана — 2 ст.л.', 'Зернистая горчица — 1 ч.л.', 'Огурец — 0.5 шт.', 'Салатные листья — 2 листа']
  },
  {
    id: 69,
    name: 'Кофейная овсянка',
    url: 'https://food.ru/recipes/272592-kofeinaja-ovsjanka',
    cuisine: 'Европейская',
    meal_type: 'breakfast',
    cooking_time_min: 15,
    calories: 244.3,
    protein: 4.74,
    fat: 16.66,
    carbs: 20.15,
    price_per_serving: 95,
    servings: 2,
    ingredients: ['Овсяные хлопья — 100 г', 'Кокосовое молоко — 200 мл', 'Вода — 100 мл', 'Молотый кофе — 1 ч.л.', 'Молочный шоколад — 40 г', 'Кокосовая стружка — 1.5 ч.л.', 'Соль — 1 щепотка']
  },
  {
    id: 70,
    name: 'Горячие тосты с яичным салатом',
    url: 'https://food.ru/recipes/272585-gorjachie-tosty-s-jaichnym-salatom',
    cuisine: 'Европейская',
    meal_type: 'breakfast',
    cooking_time_min: 30,
    calories: 192.71,
    protein: 13.45,
    fat: 11.52,
    carbs: 7.91,
    price_per_serving: 90,
    servings: 2,
    ingredients: ['Белый хлеб — 2 ломтика', 'Яйца — 4 шт.', 'Твердый сыр — 4 ломтика', 'Петрушка — 1 пучок', 'Майонез — по вкусу', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 71,
    name: 'Тост с творожным сыром и перепелиным яйцом',
    url: 'https://food.ru/recipes/zakuski/gorjachie-buterbrody?type_meal_ids=195',
    cuisine: 'Европейская',
    meal_type: 'breakfast',
    cooking_time_min: 25,
    calories: 257.43,
    protein: 8.88,
    fat: 16.63,
    carbs: 15.28,
    price_per_serving: 120,
    servings: 2,
    ingredients: ['Творожный сыр — 75 г', 'Шпинат — 70 г', 'Тостовый хлеб — 2 ломтика', 'Бекон — 3 ломтика', 'Перепелиное яйцо — 2 шт.', 'Кедровые орехи — по вкусу']
  },
  {
    id: 72,
    name: 'Манник на сметане со сгущенкой',
    url: 'https://food.ru/recipes/269518-smetannik-na-manke-1766305795',
    cuisine: 'Русская',
    meal_type: 'dessert',
    cooking_time_min: 70,
    calories: 316.96,
    protein: 7.1,
    fat: 16.61,
    carbs: 34.78,
    price_per_serving: 85,
    servings: 6,
    ingredients: ['Манная крупа — 150 г', 'Сметана 15% — 200 г', 'Пшеничная мука — 130 г', 'Сгущенное молоко — 240 г', 'Куриное яйцо — 2 шт.', 'Сливочное масло — 110 г', 'Соль — 1 г', 'Разрыхлитель теста — 1 г']
  },
  {
    id: 73,
    name: 'Блины на майонезе',
    url: 'https://food.ru/recipes/271299-bliny-na-maioneze',
    cuisine: 'Русская',
    meal_type: 'breakfast',
    cooking_time_min: 30,
    calories: 196.16,
    protein: 3.79,
    fat: 12.46,
    carbs: 17.51,
    price_per_serving: 28,
    servings: 10,
    ingredients: ['Майонез — 50 г', 'Куриное яйцо — 2 шт.', 'Сахар — 50 г', 'Пшеничная мука — 130 г', 'Вода — 400 мл', 'Подсолнечное масло — 51 мл', 'Соль — 1 г']
  },
  {
    id: 74,
    name: 'Творожные вафли с ягодами и медом',
    url: 'https://food.ru/recipes/271817-tvorozhnye-vafli-s-jagodami-i-medom',
    cuisine: 'Европейская',
    meal_type: 'breakfast',
    cooking_time_min: 30,
    calories: 280.25,
    protein: 10.28,
    fat: 17.62,
    carbs: 21.62,
    price_per_serving: 95,
    servings: 2,
    ingredients: ['Творог — 200 г', 'Яйца — 2 шт.', 'Сахар — 75 г', 'Сливочное масло — 40 г', 'Рисовая мука — 40 г', 'Разрыхлитель теста — 2.5 г', 'Соль — 1 щепотка', 'Растительное масло — 34 мл']
  },
  {
    id: 75,
    name: 'Морковные тортильи с курицей и авокадо',
    url: 'https://food.ru/recipes/271816-morkovnye-tortili-s-kuricei-i-avokado',
    cuisine: 'Европейская',
    meal_type: 'lunch',
    cooking_time_min: 40,
    calories: 129.58,
    protein: 10.85,
    fat: 8.37,
    carbs: 3.52,
    price_per_serving: 165,
    servings: 2,
    ingredients: ['Яйца — 1 шт.', 'Морковь — 100 г', 'Сыр — 30 г', 'Куриное филе — 180 г', 'Творожный сыр — 30 г', 'Рукола — 20 г', 'Огурец — 0.5 шт.', 'Авокадо — 0.5 шт.']
  },
  {
    id: 76,
    name: 'Кексы на апельсиновом соке',
    url: 'https://food.ru/recipes/271149-keksy-na-apelsinovom-soke',
    cuisine: 'Американская',
    meal_type: 'dessert',
    cooking_time_min: 75,
    calories: 326.99,
    protein: 4.78,
    fat: 21.88,
    carbs: 27.79,
    price_per_serving: 110,
    servings: 6,
    ingredients: ['Пшеничная мука — 130 г', 'Йогурт — 125 г', 'Кукурузный крахмал — 30 г', 'Растительное масло — 51 мл', 'Сахар — 75 г', 'Куриное яйцо — 1 шт.', 'Апельсин — 1 шт.', 'Ванилин — 1 г', 'Разрыхлитель теста — 5 г', 'Соль — 1 г', 'Творожный сыр — 150 г', 'Сгущенное молоко — 120 г', 'Сливочное масло — 120 г']
  },
  {
    id: 77,
    name: 'Свекольный суп на кокосовом молоке',
    url: 'https://food.ru/recipes/272803-svekolnyi-sup-na-kokosovom-moloke',
    cuisine: 'Европейская',
    meal_type: 'lunch',
    cooking_time_min: 70,
    calories: 131.94,
    protein: 1.47,
    fat: 10.97,
    carbs: 7.3,
    price_per_serving: 70,
    servings: 4,
    ingredients: ['Свекла — 130 г', 'Картофель — 120 г', 'Морковь — 100 г', 'Пассата — 200 г', 'Репчатый лук — 80 г', 'Стебель сельдерея — 22.5 г', 'Кокосовое молоко — 200 мл', 'Корень имбиря — 8 г', 'Подсолнечное масло — 34 мл', 'Соль — по вкусу']
  },
  {
    id: 78,
    name: 'Густой овощной суп со спаржей',
    url: 'https://food.ru/recipes/272791-gustoi-ovoshchnoi-sup-so-sparzhei',
    cuisine: 'Европейская',
    meal_type: 'lunch',
    cooking_time_min: 50,
    calories: 28.4,
    protein: 1.68,
    fat: 0.23,
    carbs: 5.08,
    price_per_serving: 75,
    servings: 4,
    ingredients: ['Помидор — 270 г', 'Сладкий перец — 100 г', 'Стебель сельдерея — 90 г', 'Морковь — 100 г', 'Репчатый лук — 80 г', 'Чеснок — 15 г', 'Спаржа — 34 г', 'Бульон — 400 мл', 'Замороженный горох — 125 г', 'Томатная паста — 30 г', 'Базилик — по вкусу', 'Петрушка — по вкусу', 'Фенхель — 30 г']
  },
  {
    id: 79,
    name: 'Картофельная бабка',
    url: 'https://food.ru/recipes/231027-kartofelnaja-babka-s-salom',
    cuisine: 'Белорусская',
    meal_type: 'dinner',
    cooking_time_min: 100,
    calories: 157.15,
    protein: 7.11,
    fat: 10.44,
    carbs: 8.59,
    price_per_serving: 210,
    servings: 2,
    ingredients: ['Картофель — 600 г', 'Репчатый лук — 160 г', 'Свинина — 500 г', 'Сметана — 75 г', 'Сливочное масло — 20 г', 'Соль — 2.1 г', 'Черный перец молотый — 2.5 г']
  },
  {
    id: 80,
    name: 'Грибной суп с фунчозой',
    url: 'https://food.ru/recipes/272780-gribnoi-sup-s-funchozoi',
    cuisine: 'Азиатская',
    meal_type: 'lunch',
    cooking_time_min: 65,
    calories: 38.1,
    protein: 1.05,
    fat: 1.46,
    carbs: 4.48,
    price_per_serving: 65,
    servings: 4,
    ingredients: ['Мясной бульон — 1000 мл', 'Фунчоза — 35 г', 'Грибы — 100 г', 'Репчатый лук — 40 г', 'Морковь — 50 г', 'Картофель — 120 г', 'Чеснок — 5 г', 'Соевый соус — 15 мл', 'Растительное масло — 17 мл', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 81,
    name: 'Свинина в соевом соусе',
    url: 'https://food.ru/recipes/204601-svinina-v-soevom-souse-v-duhovke',
    cuisine: 'Азиатская',
    meal_type: 'dinner',
    cooking_time_min: 200,
    calories: 262.42,
    protein: 11.03,
    fat: 14.55,
    carbs: 21.5,
    price_per_serving: 210,
    servings: 4,
    ingredients: ['Свинина — 500 г', 'Растительное масло — 17 мл', 'Корень имбиря — 50 г', 'Устричный соус — 50 г', 'Соевый соус — 30 мл', 'Мёд — 56 г', 'Рисовый уксус — 15 мл', 'Белый кунжут — по вкусу', 'Рис — 150 г']
  },
  {
    id: 104,
    name: 'Пирог из пшена с овощами',
    url: 'https://food.ru/recipes/265540-ovoshchnoi-pirog-solnce',
    cuisine: 'Русская',
    meal_type: 'dinner',
    cooking_time_min: 90,
    calories: 155.46,
    protein: 5.99,
    fat: 8.99,
    carbs: 12.61,
    price_per_serving: 105,
    servings: 6,
    ingredients: ['Творог 9% — 200 г', 'Куриное яйцо — 2 шт.', 'Соль — 7 г', 'Сахар — 16 г', 'Подсолнечное масло — 85 мл', 'Разрыхлитель теста — 5 г', 'Пшеничная мука — 150 г', 'Пшено — 45 г', 'Вода — 200 мл', 'Кабачок — 300 г', 'Помидор — 360 г', 'Полутвердый сыр — 100 г', 'Сушеные травы — 2 г', 'Смесь перцев — 1.5 г']
  },
  {
    id: 82,
    name: 'Тако с курицей и сальсой из ананаса',
    url: 'https://food.ru/recipes/272565-tako-s-kuricei-i-salsoi-iz-ananasa',
    cuisine: 'Мексиканская',
    meal_type: 'dinner',
    cooking_time_min: 40,
    calories: 128.1,
    protein: 6.77,
    fat: 2.56,
    carbs: 18.09,
    price_per_serving: 145,
    servings: 8,
    ingredients: ['Кукурузная лепешка — 520 г', 'Копченая куриная грудка — 400 г', 'Краснокочанная капуста — 50 г', 'Сыр фета — 50 г', 'Острый томатный соус — 25 г', 'Консервированный ананас — 200 г', 'Красный болгарский перец — 150 г', 'Красный лук — 37.5 г', 'Перец халапеньо — 15 г', 'Кинза — 12 г', 'Лайм — 60 г', 'Соль — 1 г']
  },
  {
    id: 83,
    name: 'Свиной шашлык в гранатовом маринаде',
    url: 'https://food.ru/recipes/260810-shashlyk-v-granatovom-marinade-1756459029',
    cuisine: 'Кавказская',
    meal_type: 'dinner',
    cooking_time_min: 180,
    calories: 206.01,
    protein: 7.49,
    fat: 16.63,
    carbs: 6.08,
    price_per_serving: 320,
    servings: 4,
    ingredients: ['Свиная шея — 1000 г', 'Гранатовый сок — 500 мл', 'Репчатый лук — 400 г', 'Перец чили — 7 г', 'Черный перец молотый — 5 г', 'Соль — 7 г']
  },
  {
    id: 84,
    name: 'Картофельное суфле с беконом и помидором',
    url: 'https://food.ru/recipes/198564-kartoshechka-kak-u-babushki-1700150099',
    cuisine: 'Европейская',
    meal_type: 'dinner',
    cooking_time_min: 100,
    calories: 142.83,
    protein: 6.53,
    fat: 8.96,
    carbs: 8.94,
    price_per_serving: 135,
    servings: 4,
    ingredients: ['Картофель — 480 г', 'Сырокопченый бекон — 68 г', 'Куриное яйцо — 2 шт.', 'Помидоры черри — 140 г', 'Репчатый лук — 80 г', 'Пармезан — 100 г', 'Молоко 2.5% — 36 мл', 'Сливочное масло — 20 г', 'Соль — 3.5 г']
  },
  {
    id: 85,
    name: 'Хлебный пирог для пикника',
    url: 'https://food.ru/recipes/272542-hlebnyi-pirog-dlja-piknika',
    cuisine: 'Европейская',
    meal_type: 'snack',
    cooking_time_min: 200,
    calories: 288.44,
    protein: 9.62,
    fat: 18.03,
    carbs: 22.15,
    price_per_serving: 190,
    servings: 4,
    ingredients: ['Белый хлеб — 400 г', 'Плавленый сыр — 144 г', 'Болгарский перец — 100 г', 'Ветчина — 100 г', 'Салат айсберг — 98 г', 'Салями — 100 г', 'Вяленые помидоры — 50 г', 'Базилик — 28 г', 'Майонез — 100 г', 'Соус песто — 56 г']
  },
  {
    id: 86,
    name: 'Шампиньоны с сыром в беконе',
    url: 'https://food.ru/recipes/145440-farshirovannye-shampinony-v-bekone-1657920598',
    cuisine: 'Русская',
    meal_type: 'snack',
    cooking_time_min: 55,
    calories: 264.07,
    protein: 7.92,
    fat: 23.49,
    carbs: 2.59,
    price_per_serving: 185,
    servings: 2,
    ingredients: ['Шампиньоны — 192 г', 'Моцарелла для пиццы — 50 г', 'Сырокопченый бекон — 204 г', 'Соевый соус — 10 мл', 'Чеснок — 10 г', 'Майонез — 25 г', 'Копченая паприка — 14 г']
  },
  {
    id: 87,
    name: 'Куриные ножки с гречкой в духовке',
    url: 'https://food.ru/recipes/vtorye-bliuda/kurica-v-duhovke?calories=up_to_200',
    cuisine: 'Русская',
    meal_type: 'dinner',
    cooking_time_min: 55,
    calories: 155.83,
    protein: 8.9,
    fat: 8.07,
    carbs: 12.71,
    price_per_serving: 105,
    servings: 4,
    ingredients: ['Куриная голень — 480 г', 'Вода — 400 мл', 'Гречка — 247.5 г', 'Растительное масло — 34 мл', 'Репчатый лук — 80 г', 'Морковь — 100 г', 'Перец чили — 5 г', 'Чеснок — 10 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 88,
    name: 'Запеченный картофель с брокколи и соусом дзадзики',
    url: 'https://food.ru/recipes/272666-zapechenyi-kartofel-s-brokkoli-i-sousov-dzadzyki',
    cuisine: 'Греческая',
    meal_type: 'dinner',
    cooking_time_min: 20,
    calories: 89.87,
    protein: 2.68,
    fat: 5.03,
    carbs: 8.66,
    price_per_serving: 145,
    servings: 2,
    ingredients: ['Картофель — 500 г', 'Брокколи — 400 г', 'Лимон — 120 г', 'Сушеный орегано — 1.5 г', 'Сушеный тимьян — 1 г', 'Сушеный репчатый лук — 4 г', 'Зира — 3 г', 'Оливковое масло — 51 мл', 'Кунжутный соус — 15 г', 'Мёд — 7 г', 'Соль — 5.6 г', 'Черный перец молотый — 3.5 г', 'Огурец — 120 г', 'Греческий йогурт — 240 г', 'Укроп — 12 г', 'Чеснок — 5 г', 'Лимонный сок — 27 мл', 'Помидоры черри — 160 г', 'Миндаль — 30 г']
  },
  {
    id: 89,
    name: 'Бургер на хрустящей капусте',
    url: 'https://food.ru/recipes/271282-burger-s-dvoynoy-kotletoy',
    cuisine: 'Американская',
    meal_type: 'dinner',
    cooking_time_min: 50,
    calories: 187.45,
    protein: 9,
    fat: 14.19,
    carbs: 5.61,
    price_per_serving: 165,
    servings: 4,
    ingredients: ['Говяжий фарш — 400 г', 'Белокочанная капуста — 300 г', 'Подсолнечное масло — 51 мл', 'Соль — 14 г', 'Черный перец молотый — 3 г', 'Плавленый сыр — 72 г', 'Маринованные огурцы — 50 г', 'Красный лук — 24.75 г', 'Кетчуп — 44 г', 'Горчица — 50 г']
  },
  {
    id: 90,
    name: 'Капустная лазанья',
    url: 'https://food.ru/recipes/257771-lazania-s-ovoshchami-1752949342',
    cuisine: 'Русская',
    meal_type: 'dinner',
    cooking_time_min: 80,
    calories: 155.23,
    protein: 7.57,
    fat: 10.04,
    carbs: 8.74,
    price_per_serving: 145,
    servings: 6,
    ingredients: ['Сливочное масло — 120 г', 'Капуста — 890 г', 'Пармезан — 100 г', 'Томатная паста — 90 г', 'Куриный фарш — 500 г', 'Репчатый лук — 80 г', 'Чеснок — 20 г', 'Панировочные сухари — 150 г', 'Морковь — 200 г', 'Растительное масло — 34 мл', 'Соль — по вкусу', 'Сливки 10% — 100 мл', 'Куриное яйцо — 1 шт.', 'Твердый сыр — 75 г']
  },
  {
    id: 91,
    name: 'Паста с овощами в одной сковороде',
    url: 'https://food.ru/recipes/236682-pasta-s-ovoshchami-1733319354',
    cuisine: 'Итальянская',
    meal_type: 'dinner',
    cooking_time_min: 30,
    calories: 212.92,
    protein: 6.51,
    fat: 13.67,
    carbs: 15.72,
    price_per_serving: 125,
    servings: 3,
    ingredients: ['Паста фетучини — 160 г', 'Помидоры черри — 200 г', 'Красный лук — 75 г', 'Шпинат — 30 г', 'Чеснок — 10 г', 'Сливки 20% — 105 мл', 'Овощной бульон — 100 мл', 'Сыр голландский — 100 г', 'Прованские травы — по вкусу', 'Хлопья чили — по вкусу', 'Оливковое масло — 51 мл', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 92,
    name: 'Энчилада с курицей и чили',
    url: 'https://food.ru/recipes/272051-Enchilada-s-kuricei-i-chili',
    cuisine: 'Мексиканская',
    meal_type: 'dinner',
    cooking_time_min: 50,
    calories: 152.85,
    protein: 9.83,
    fat: 7.71,
    carbs: 11.14,
    price_per_serving: 210,
    servings: 5,
    ingredients: ['Куриный фарш — 800 г', 'Тортилья — 300 г', 'Полутвердый сыр — 300 г', 'Репчатый лук — 160 г', 'Чеснок — 30 г', 'Перец чили — 15 г', 'Помидоры в собственном соку — 700 г', 'Сушеный орегано — 3 г', 'Зира — 3 г', 'Кориандр — 5 г', 'Растительное масло — 51 мл', 'Кинза — 15 г', 'Красный жгучий перец — 10 г', 'Сахар — 8 г', 'Черный перец молотый — 5 г', 'Соль — 14 г']
  },
  {
    id: 93,
    name: 'Курица с черносливом в томатном соусе',
    url: 'https://food.ru/recipes/271749-kurica-s-tomatami-i-chernoslivom',
    cuisine: 'Европейская',
    meal_type: 'dinner',
    cooking_time_min: 40,
    calories: 173.32,
    protein: 14.87,
    fat: 10.43,
    carbs: 5.23,
    price_per_serving: 165,
    servings: 4,
    ingredients: ['Мясо куриного бедра — 800 г', 'Чернослив — 64 г', 'Репчатый лук — 80 г', 'Чеснок — 5 г', 'Томатная паста — 30 г', 'Сахар — 8 г', 'Вода — 150 мл', 'Растительное масло — 34 мл', 'Петрушка — 4 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу', 'Рис — по желанию']
  },
  {
    id: 94,
    name: 'Запеченная паста с колбасками',
    url: 'https://food.ru/recipes/vtorye-bliuda/makarony-s-kolbasoi',
    cuisine: 'Европейская',
    meal_type: 'dinner',
    cooking_time_min: 85,
    calories: 279.4,
    protein: 13.38,
    fat: 16.55,
    carbs: 20.58,
    price_per_serving: 220,
    servings: 6,
    ingredients: ['Спагетти — 500 г', 'Краковская колбаса — 400 г', 'Красный болгарский перец — 450 г', 'Моцарелла — 400 г', 'Пармезан — 100 г', 'Растительное масло — 51 мл', 'Итальянские травы — 4 г', 'Перец чили молотый — 5 г', 'Черный перец молотый — 2.5 г', 'Соль — 7 г', 'Оливки — 50 г', 'Вяленые помидоры — 50 г', 'Маринованный перец халапеньо — 30 г']
  },
  {
    id: 95,
    name: 'Котлеты-сердечки',
    url: 'https://food.ru/recipes/271702-kotlety-serdechki',
    cuisine: 'Русская',
    meal_type: 'dinner',
    cooking_time_min: 40,
    calories: 264.83,
    protein: 13.16,
    fat: 22.94,
    carbs: 1.59,
    price_per_serving: 135,
    servings: 4,
    ingredients: ['Свинина — 500 г', 'Репчатый лук — 80 г', 'Чеснок — 5 г', 'Растительное масло — 34 мл', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 96,
    name: 'Хачапури-бургеры',
    url: 'https://food.ru/recipes/271014-hachapuri-burger',
    cuisine: 'Грузинская',
    meal_type: 'dinner',
    cooking_time_min: 120,
    calories: 251.46,
    protein: 11.68,
    fat: 12.75,
    carbs: 21.48,
    price_per_serving: 240,
    servings: 8,
    ingredients: ['Говяжий фарш — 800 г', 'Репчатый лук — 160 г', 'Сулугуни — 600 г', 'Помидор — 90 г', 'Соус сацебели — 64 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу', 'Пшеничная мука — 975 г', 'Молоко — 500 мл', 'Сливочное масло — 125 г', 'Сухие дрожжи — 10 г', 'Желток куриного яйца — 1 шт.']
  },
  {
    id: 105,
    name: 'Крупенник из гречки',
    url: 'https://food.ru/recipes/271136-krupennik-iz-grechki',
    cuisine: 'Русская',
    meal_type: 'dessert',
    cooking_time_min: 65,
    calories: 164.01,
    protein: 7.25,
    fat: 7.18,
    carbs: 18.92,
    price_per_serving: 95,
    servings: 4,
    ingredients: ['Гречка — 330 г', 'Вода — 700 мл', 'Творог — 400 г', 'Куриное яйцо — 2 шт.', 'Сахар — 100 г', 'Сливочное масло — 100 г', 'Панировочные сухари — 30 г', 'Соль — по вкусу']
  },
  {
    id: 106,
    name: 'Капустные вареники',
    url: 'https://food.ru/recipes/vtorye-bliuda/vareniki?calories=up_to_200',
    cuisine: 'Украинская',
    meal_type: 'dinner',
    cooking_time_min: 60,
    calories: 184.78,
    protein: 4.4,
    fat: 7.2,
    carbs: 25.3,
    price_per_serving: 65,
    servings: 6,
    ingredients: ['Вода — 200 мл', 'Сливочное масло — 50 г', 'Сметана 20% — 50 г', 'Пшеничная мука — 500 г', 'Белокочанная капуста — 445 г', 'Репчатый лук — 80 г', 'Морковь — 100 г', 'Растительное масло — 51 мл', 'Томатная паста — 45 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 107,
    name: 'Конвертик из куриного фарша с томатами и сыром',
    url: 'https://food.ru/recipes/271811-kurinye-konvertiki-s-tomatami-i-syrom',
    cuisine: 'Европейская',
    meal_type: 'dinner',
    cooking_time_min: 40,
    calories: 179.02,
    protein: 14.24,
    fat: 6.6,
    carbs: 16.77,
    price_per_serving: 180,
    servings: 1,
    ingredients: ['Куриный фарш — 400 г', 'Кетчуп — 66 г', 'Плавленый сыр — 72 г', 'Шпинат — 15 г', 'Панировочные сухари — 100 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу', 'Сушеный чеснок — по вкусу']
  },
  {
    id: 108,
    name: 'Энчилада с фаршем и фасолью',
    url: 'https://food.ru/recipes/272052-enchilada-s-farshem',
    cuisine: 'Мексиканская',
    meal_type: 'dinner',
    cooking_time_min: 40,
    calories: 183.44,
    protein: 8.05,
    fat: 10.16,
    carbs: 14.33,
    price_per_serving: 195,
    servings: 4,
    ingredients: ['Тортилья — 480 г', 'Чеддер — 200 г', 'Петрушка — 6 г', 'Сушеный чеснок — 3 г', 'Луковый порошок — 3 г', 'Зира — 3 г', 'Сладкая паприка — 14 г', 'Сушеный орегано — 10 г', 'Кайенский перец — 1 г', 'Пассата — 300 г', 'Куриный бульон — 500 мл', 'Пшеничная мука — 45 г', 'Оливковое масло — 68 мл', 'Соль — 1 г', 'Черный перец молотый — 1 г', 'Говяжий фарш — 500 г', 'Консервированная красная фасоль — 400 г', 'Чеснок — 10 г', 'Репчатый лук — 80 г']
  },
  {
    id: 109,
    name: 'Куриный суп с белой фасолью',
    url: 'https://food.ru/recipes/190210-sup-fasolevyi-s-kuritsei',
    cuisine: 'Грузинская',
    meal_type: 'lunch',
    cooking_time_min: 60,
    calories: 141.86,
    protein: 14.6,
    fat: 6.54,
    carbs: 7.37,
    price_per_serving: 120,
    servings: 6,
    ingredients: ['Мясо куриного бедра — 750 г', 'Консервированная белая фасоль — 400 г', 'Репчатый лук — 80 г', 'Чеснок — 10 г', 'Аджика — 50 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу', 'Кинза — 30 г']
  },
  {
    id: 110,
    name: 'Суп с машем и фрикадельками',
    url: 'https://food.ru/recipes/271855-sup-s-mashem-i-frikdelkami',
    cuisine: 'Ближневосточная',
    meal_type: 'lunch',
    cooking_time_min: 70,
    calories: 24.61,
    protein: 2.74,
    fat: 0.3,
    carbs: 2.57,
    price_per_serving: 75,
    servings: 4,
    ingredients: ['Маш — 100 г', 'Филе куриной грудки — 240 г', 'Картошка — 240 г', 'Морковь — 100 г', 'Репчатый лук — 80 г', 'Петрушка — 20 г', 'Вода — 1700 мл', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 111,
    name: 'Томатный суп с фасолью и курицей',
    url: 'https://food.ru/recipes/270786-tomatnyi-sup-s-fasoliu-i-kuricei',
    cuisine: 'Европейская',
    meal_type: 'lunch',
    cooking_time_min: 60,
    calories: 63.86,
    protein: 4.17,
    fat: 3.48,
    carbs: 3.73,
    price_per_serving: 95,
    servings: 6,
    ingredients: ['Куриная голень — 720 г', 'Картошка — 360 г', 'Красный болгарский перец — 150 г', 'Морковь — 100 г', 'Репчатый лук — 80 г', 'Подсолнечное масло — 34 мл', 'Соль — 7 г', 'Черный перец молотый — 2.5 г', 'Лавровый лист — 2 г', 'Вода — 2000 мл', 'Консервированная белая фасоль в томатном соусе — 500 г']
  },
  {
    id: 112,
    name: 'Ананас, фаршированный креветками',
    url: 'https://food.ru/recipes/100639-ris-po-vetnamski-s-krevetkami-i-ananasom-1643303035',
    cuisine: 'Азиатская',
    meal_type: 'dinner',
    cooking_time_min: 100,
    calories: 87.49,
    protein: 3.02,
    fat: 2.54,
    carbs: 12.58,
    price_per_serving: 290,
    servings: 2,
    ingredients: ['Ананас — 1400 г', 'Креветки — 300 г', 'Рис жасмин — 180 г', 'Вода — 500 мл', 'Чеснок — 10 г', 'Перец чили — 15 г', 'Зеленый лук — 50 г', 'Лайм — 60 г', 'Корень имбиря — 20 г', 'Жареный кешью — 20 г', 'Подсолнечное масло — 51 мл', 'Рыбный соус — 36 мл', 'Молотая куркума — 6 г', 'Белый перец молотый — 3 г', 'Соль — по вкусу']
  },
  {
    id: 113,
    name: 'Курица в цитрусовом маринаде',
    url: 'https://food.ru/recipes/242756-bedryshki-kurinye-v-gorchichno-chesnochnom-marinade-1738323240',
    cuisine: 'Европейская',
    meal_type: 'dinner',
    cooking_time_min: 210,
    calories: 146.21,
    protein: 11.32,
    fat: 9.58,
    carbs: 3.54,
    price_per_serving: 185,
    servings: 6,
    ingredients: ['Курица — 1500 г', 'Апельсин — 500 г', 'Лимон — 120 г', 'Чеснок — 30 г', 'Мед — 28 г', 'Соевый соус — 30 мл', 'Сушеный орегано — 3 г', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  },
  {
    id: 114,
    name: 'Перловая каша в топленом молоке с курицей и сыром',
    url: 'https://food.ru/recipes/271609-perlovaja-kasha-v-toplenom-moloke-s-kuricei-i-syrom-',
    cuisine: 'Русская',
    meal_type: 'dinner',
    cooking_time_min: 80,
    calories: 155.94,
    protein: 8.01,
    fat: 9.2,
    carbs: 10.5,
    price_per_serving: 170,
    servings: 4,
    ingredients: ['Куриное филе — 300 г', 'Топленое молоко — 70 мл', 'Перловка — 180 г', 'Вода — 500 мл', 'Соль — 3.5 г', 'Подсолнечное масло — 17 мл', 'Сливки 33% — 210 мл', 'Сыр с голубой плесенью — 100 г']
  },
  {
    id: 115,
    name: 'Ризотто из пшена с креветками',
    url: 'https://food.ru/recipes/271608-rizotto-iz-pshena-s-krevetkami-',
    cuisine: 'Итальянская',
    meal_type: 'dinner',
    cooking_time_min: 60,
    calories: 118.81,
    protein: 4.94,
    fat: 6.88,
    carbs: 8.65,
    price_per_serving: 210,
    servings: 3,
    ingredients: ['Королевские креветки — 120 г', 'Тыква — 300 г', 'Пшено — 130 г', 'Сливочное масло — 50 г', 'Пармезан — 50 г', 'Белое сухое вино — 100 мл', 'Репчатый лук — 40 г', 'Чеснок — 10 г', 'Куриный бульон — 600 мл', 'Подсолнечное масло — 34 мл', 'Соль — 3.5 г', 'Черный перец молотый — 1 г', 'Сыр страчателла — по желанию', 'Тархун — по желанию']
  },
  {
    id: 116,
    name: 'Теплый салат с брокколи, перловкой и курицей',
    url: 'https://food.ru/recipes/271606-teplyi-salat-s-brokkoli-perlovkoi-i-kuricei-',
    cuisine: 'Европейская',
    meal_type: 'lunch',
    cooking_time_min: 70,
    calories: 90.42,
    protein: 6.52,
    fat: 3.39,
    carbs: 8.93,
    price_per_serving: 135,
    servings: 4,
    ingredients: ['Куриное филе — 400 г', 'Кабачок — 300 г', 'Брокколи — 227.5 г', 'Петрушка — 20 г', 'Зеленый лук — 15 г', 'Перловка — 180 г', 'Вода — 600 мл', 'Бальзамический уксус — 15 г', 'Соль — 4 г', 'Оливковое масло — 51 мл', 'Копченая паприка — 7 г', 'Черный перец молотый — 2.5 г', 'Кайенский перец — 1 г', 'Сушеный чеснок — 1.5 г', 'Лимон — 39.6 г', 'Дижонская горчица — 25 г']
  },
  {
    id: 117,
    name: 'Плов со свининой и финиками',
    url: 'https://food.ru/recipes/212481-plov-so-svininoi-na-skovorode-1711612912',
    cuisine: 'Восточная',
    meal_type: 'dinner',
    cooking_time_min: 60,
    calories: 242.56,
    protein: 9.86,
    fat: 13.53,
    carbs: 20.62,
    price_per_serving: 185,
    servings: 6,
    ingredients: ['Рис — 360 г', 'Свинина — 1000 г', 'Морковь — 200 г', 'Репчатый лук — 240 г', 'Чеснок — 40 г', 'Финики — 100 г', 'Зира — 3 г', 'Молотый кориандр — 1 г', 'Растительное масло — 51 мл', 'Барбарис — по вкусу', 'Соль — по вкусу', 'Черный перец молотый — по вкусу']
  }
];
